config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :clients
  resources :companies
  get 'home/index'

  devise_for :users, controllers: { invitations: 'users/invitations' }

  authenticated :user do
    root to: 'home#index', as: :user_authenticated
  end

  unauthenticated :user do
    root to: 'landing#index'
  end

end

app/models/client.rb
class Client < ApplicationRecord
    belongs_to :company
    has_many :client_appointments
    has_many :client_appointment_products, through: :client_appointments

    validates :names, :ap_pat, :tel, presence: true
    validates :tel, presence: true, numericality: { only_integer: true }
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  before_action  :authenticate_user!, :authenticate_has_company!
  before_action :set_client, only: %i[ show edit update destroy ]
  before_action :set_current_user
  # GET /clients or /clients.json
  def index
    @clients = Client.where(:company_id => @current_user.user_company.company_id)
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)
    @client.company_id = @current_user.user_company.company_id

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      client = Client.find(params[:id])
      if client.company_id == @current_user.user_company.company.id
        @client = client
      else 
        redirect_to root_path
      end
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:names, :ap_pat, :ap_mat, :tel, :channel, :company_id)
    end


end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :names %>
    <%= form.text_field :names, id: :client_names %>
  </div>

  <div class="field">
    <%= form.label :ap_pat %>
    <%= form.text_field :ap_pat, id: :client_ap_pat %>
  </div>

  <div class="field">
    <%= form.label :ap_mat %>
    <%= form.text_field :ap_mat, id: :client_ap_mat %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel, id: :client_tel %>
  </div>

  <div class="field">
    <%= form.label :channel %>
    <%= form.text_field :channel, id: :client_channel %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Names</th>
      <th>Ap pat</th>
      <th>Ap mat</th>
      <th>Tel</th>
      <th>Channel</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.names %></td>
        <td><%= client.ap_pat %></td>
        <td><%= client.ap_mat %></td>
        <td><%= client.tel %></td>
        <td><%= client.channel %></td>
        <td><%= client.company_id %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Names:</strong>
  <%= @client.names %>
</p>

<p>
  <strong>Ap pat:</strong>
  <%= @client.ap_pat %>
</p>

<p>
  <strong>Ap mat:</strong>
  <%= @client.ap_mat %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @client.tel %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @client.channel %>
</p>

<p>
  <strong>Company:</strong>
  <%= @client.company_id %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>